### ISSUE TITLE
Add new tool to escape Unicode

### ISSUE THREAD

**Issue by jspenguin2017** [NanoAdblocker/NanoToolkit#1]
The tool should be able to convert Unicode characters to their Unicode escape sequence.

**Comment by kulfoon** [comment]
Hey, and what about these converters: 
CONVERTER 1: `https://onlineunicodetools.com/escape-unicode`
CONVERTER 2: `https://www.mobilefish.com/services/unicode_escape_sequence_converter/unicode_escape_sequence_converter.php`

**Comment by jspenguin2017** [comment]
Actually, this was implemented already: https://github.com/NanoAdblocker/NanoToolkit/commit/e115b65eb26f8e9ea36ecf4a6bac42353a54b670

**Comment by kulfoon** [comment]
Yes I saw it already before creating my comment, just wasn't sure whether it was the same or completed, as the issue was still open here, also wanted to ask about the others as a comparison and whether there is a need for creating such tool at all given the fact such tools exist already.

**Comment by jspenguin2017** [comment]
It is not the same as the first tool that you linked, but is similar to the second one. It was completed but I forgot to close this issue. Although it is similar to the second tool, they are not exactly the same. The converter is quite easy to implement so I made one that does exactly what I wanted.

**Comment by kulfoon** [comment]
> It is not the same as the first tool that you linked

Are you sure you didn't miss selecting a proper option before conversion:

<details not-open>
<summary>screenshoot</summary>


![capture_007_23-05-2020_08-38-24](https://user-images.githubusercontent.com/43844449/82723788-a810e980-9cd1-11ea-88c8-482c69ef5544.gif)
</details>

or perhaps you still had another difference in mind.

**Comment by jspenguin2017** [comment]
I selected the proper option, but it encodes every character instead of only non-ASCII characters.

**Comment by kulfoon** [comment]
Ok then, I got it.
